app:
  name: college-app

replicaCount: 1

image:
  repository: likhithabhogyam/duniversity
  tag: v1.0.0
  imagePullPolicy: IfNotPresent

ports:
  containerPort: 3000

mysql:
  name: mysql

serviceName: mysql-service

replicas: 1
minReadySeconds: 10

terminationGracePeriodSeconds: 10

mysqlImagename: mysql:5.7

ports:
  containerPort: 3306