apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql   

  serviceName: "mysql-service"   

  replicas: 3
  minReadySeconds: 10

  template:
    metadata:
      labels:
        app: mysql   

    spec:
      terminationGracePeriodSeconds: 10

      containers:
      - name: mysql
        image: mysql:5.7

        ports:
        - containerPort: 3306
          name: mysql

        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
          requests:
            memory: "256Mi"
            cpu: "100m"

        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD

        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER

        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD

        volumeMounts:
        - name: likhitha-data
          mountPath: /var/lib/mysql

  volumeClaimTemplates:
  - metadata:
      name: likhitha-data
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: duniversity-storage
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  clusterIP: None