apiVersion: pxc.percona.com/v1
kind: PerconaXtraDBCluster
metadata:
  name: my-cluster
spec:
  crVersion: 1.14.0

  secretsName: mysql-secret

  pxc:
    size: 3
    image: percona/percona-xtradb-cluster:8.0

    volumeSpec:
      persistentVolumeClaim:
        accessModes: ["ReadWriteOnce"]
        storageClassName: duniversity-storage  
        resources:
          requests:
            storage: 5Gi

  proxysql:
    enabled: true
    size: 1
    image: percona/percona-xtradb-cluster-operator:1.14.0-proxysql